###

GET http://localhost:8080/comments

###

POST http://localhost:8080/comments
content-Type: application/json

{
    "user": "Hasid",
    "postId": "111111111111",
    "content": "Beautiful post"
}

###

PUT  http://localhost:8080/posts/6744d3120f3232bdcdfa135e
content-Type: application/json

{
    "title": "BFF",
    "content": "Amazing",
    "owner": "Tomer Hasid"
}

###


GET http://localhost:8080/posts?sender=tomer

###

PUT  http://localhost:8080/comments/6734b0c818a1cf8344804554
content-Type: application/json

{
    "postId": "111111111111111111111111",
    "content": "Updated comment"
}

###

DELETE http://localhost:8080/comments/6734b0c818a1cf8344804554

###

POST http://localhost:8080/posts
content-Type: application/json

{
    "title": "Best course ever",
    "content": "This course is amazing",
    "owner": "Tomer Shomron & Omer Hasid"
}

###

GET http://localhost:8080/posts?sender=tomer

###

GET http://localhost:8080/posts?sender=tomer

###

GET http://localhost:8080/posts
###

GET http://localhost:8080/posts/67437487809a2059cef4d126

###

DELETE http://localhost:8080/posts/6744d3bea79f6c0d99ce79d3

