###

POST http://localhost:8080/comments
content-Type: application/json

{
    "user": "Hasid",
    "postId": "111111111111",
    "content": "Beautiful post"
}


###

POST http://localhost:8080/comments
content-Type: application/json

{
    "title": "Best course ever",
    "content": "This course is amazing",
    "owner": "Tomer Shomron & Omer Hasid"
}

###

GET http://localhost:8080/posts?sender=tomer
